version: '3.1'

services:
  java_app:
    container_name: java_app
    image: cyanskyyy/java_app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://java_db:5432/simple_crm
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:15.5-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simple_crm
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
